pub enum Region {
    AfSouth1,
    ApEast1,
    ApEast2,
    ApNortheast1,
    ApNortheast2,
    ApNortheast3,
    ApSouth1,
    ApSouth2,
    ApSoutheast1,
    ApSoutheast2,
    ApSoutheast3,
    ApSoutheast4,
    ApSoutheast5,
    ApSoutheast6,
    ApSoutheast7,
    CaCentral1,
    CaWest1,
    EuCentral1,
    EuCentral2,
    EuNorth1,
    EuSouth1,
    EuSouth2,
    EuWest1,
    EuWest2,
    EuWest3,
    IlCentral1,
    MeCentral1,
    MeSouth1,
    MxCentral1,
    SaEast1,
    UsEast1,
    UsEast2,
    UsWest1,
    UsWest2,
}

impl From<Region> for String {
    fn from(value: Region) -> Self {
        match value {
            Region::AfSouth1 => "af-south-1".to_string(),
            Region::ApEast1 => "ap-east-1".to_string(),
            Region::ApEast2 => "ap-east-2".to_string(),
            Region::ApNortheast1 => "ap-northeast-1".to_string(),
            Region::ApNortheast2 => "ap-northeast-2".to_string(),
            Region::ApNortheast3 => "ap-northeast-3".to_string(),
            Region::ApSouth1 => "ap-south-1".to_string(),
            Region::ApSouth2 => "ap-south-2".to_string(),
            Region::ApSoutheast1 => "ap-southeast-1".to_string(),
            Region::ApSoutheast2 => "ap-southeast-2".to_string(),
            Region::ApSoutheast3 => "ap-southeast-3".to_string(),
            Region::ApSoutheast4 => "ap-southeast-4".to_string(),
            Region::ApSoutheast5 => "ap-southeast-5".to_string(),
            Region::ApSoutheast6 => "ap-southeast-6".to_string(),
            Region::ApSoutheast7 => "ap-southeast-7".to_string(),
            Region::CaCentral1 => "ca-central-1".to_string(),
            Region::CaWest1 => "ca-west-1".to_string(),
            Region::EuCentral1 => "eu-central-1".to_string(),
            Region::EuCentral2 => "eu-central-2".to_string(),
            Region::EuNorth1 => "eu-north-1".to_string(),
            Region::EuSouth1 => "eu-south-1".to_string(),
            Region::EuSouth2 => "eu-south-2".to_string(),
            Region::EuWest1 => "eu-west-1".to_string(),
            Region::EuWest2 => "eu-west-2".to_string(),
            Region::EuWest3 => "eu-west-3".to_string(),
            Region::IlCentral1 => "il-central-1".to_string(),
            Region::MeCentral1 => "me-central-1".to_string(),
            Region::MeSouth1 => "me-south-1".to_string(),
            Region::MxCentral1 => "mx-central-1".to_string(),
            Region::SaEast1 => "sa-east-1".to_string(),
            Region::UsEast1 => "us-east-1".to_string(),
            Region::UsEast2 => "us-east-2".to_string(),
            Region::UsWest1 => "us-west-1".to_string(),
            Region::UsWest2 => "us-west-2".to_string(),
        }
    }
}
